## Writing Pythn loops is slow
Strategies:

- `ufuncs` for element-wise operations
- `aggregations` for array summarization
- `broadcasting` for combining arrays
- `slicing`, `masking`, and `fancy indexing` for selecting and operating on subsets

---


# numpy UFUNC example - much faster element-wise iterations
---

In [177]:
import numpy as np

In [178]:
a = list(range(100000))

In [179]:
# ufunc example
def ufunc_example(a):
    b = np.array(a)
    c = b + 5
    return c


In [180]:
# ufunc example
def ufunc_example2(np_array: np.array):
    c = np_array + 5
    return c

In [181]:
print("comprehension")
%timeit [val +5 for val in a]

comprehension
3.99 ms ± 33.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [182]:
print("lambda")
%timeit  list(map(lambda x: x +5, a))

lambda
6.19 ms ± 98.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [183]:
print("ufunc")
%timeit  ufunc_example(a)

ufunc
4.91 ms ± 50.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [184]:
print("ufunc wihout overhead")
b = np.array(a)
%timeit  ufunc_example2(b)

ufunc wihout overhead
20 µs ± 274 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# numpy AGGREGATIONS example - much faster element-wise iterations
---

In [185]:
from random import random
array = [random() for i in range(100000)]
np_array = np.array(array)

In [186]:
print("min of an array")
%timeit min(array)

min of an array
1.2 ms ± 18.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [187]:
print("min of a numpy array")
%timeit np_array.min()

min of a numpy array
18.4 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [188]:
M = np.random.randint(0,10,(3,5))
M

array([[0, 4, 8, 9, 4],
       [1, 3, 8, 9, 8],
       [2, 5, 1, 5, 9]])

In [189]:
print("sum of all elements")
M.sum()

sum of all elements


76

In [190]:
print("sum of all columns")
M.sum(axis=0)

sum of all columns


array([ 3, 12, 17, 23, 21])

In [191]:
print("sum of all rows")
M.sum(axis=1)

sum of all rows


array([25, 29, 22])

In [192]:
# Broadcasting

In [193]:
print("add to range [0,1,2]")
np.arange(3) + 5

add to range [0,1,2]


array([5, 6, 7])

In [194]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [195]:
p = np.arange(3)
y = p.reshape(3,1)
z = np.arange(3)
print("first array\n", y)
print("reshaped\n", y)

print("second array\n",z)
print("sum", y + z)

first array
 [[0]
 [1]
 [2]]
reshaped
 [[0]
 [1]
 [2]]
second array
 [0 1 2]
sum [[0 1 2]
 [1 2 3]
 [2 3 4]]


# Masking
---

In [209]:
L = np.array([2,3,5,7,11])
mask = np.array([False, True, True, False, False])
L[mask]

array([3, 5])

In [210]:
mask2 = (L < 4) | (L > 10)
L[mask2]

array([ 2,  3, 11])

# Fancy Indexing
---

In [211]:
L = np.array([2,3,5,7,11])
ind = [0,4,2]
L[ind]

array([ 2, 11,  5])

In [216]:
M = np.arange(6)
N = M.reshape(2,3)
N

array([[0, 1, 2],
       [3, 4, 5]])

In [219]:
N[:,1]

array([1, 4])

## Mixing indexing and slices `M[[1,0]]` flips the 1, then 0 rows, and slice `-1:` takes the last columns

In [240]:
print("Mixing fancy indexing and slices M[[1,0]] flips the 1, then 0 rows, and  -1: takes the last columns")
import numpy as np
M = np.arange(6).reshape(2,3)
M[[1,0], -1:]

Mixing fancy indexing and slices M[[1,0]] flips the 1, then 0 rows, and  -1: takes the last columns


array([[5],
       [2]])

In [252]:
print("Mixing masking and slices M[[1,0]] M.sum(axis=1) <= 3 gets rows with sum > 4, and  1: slices out column 0")
import numpy as np
M = np.arange(6).reshape(2,3)
M[M.sum(axis=1) <= 3, 1:]

Mixing masking and slices M[[1,0]] M.sum(axis=1) <= 3 gets rows with sum > 4, and  1: slices out column 0


array([[1, 2]])